import { PropsWithChildren } from 'react'
import s from './PageWrapper.module.scss'
import Head from 'next/head'
import { useThemeContext } from '@/components/ThemeProvider/Theme'
import clsx from 'clsx'

type PropsType = {
  title?: string
}

export const PageWrapper = (props: PropsWithChildren<PropsType>) => {
  const { children } = props
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={clsx(s.main)}>{children}</div>
    </>
  )
}
